import { Geist, Geist_Mono, Jersey_10 } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
    src: "../public/Geist-VariableFont_wght.ttf",
    variable: "--font-geist-sans",
});

const geistMono = localFont({
    src: "../public/GeistMono-VariableFont_wght.ttf",
    variable: "--font-geist-mono",
});

const jersey10 = localFont({
    src: "../public/Jersey10-Regular.ttf",
    variable: "--font-jersey",
});

const pfStardust = localFont({
    src: "/fonts/PFBold.ttf",
    variable: "--font-stardust",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${pfStardust.variable} ${geistMono.variable} ${jersey10.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
